export default {
    AUTH_SERVICE_URL: process.env.AUTH_SERVICE_URL,
    PRODUCTOS_SERVICE_URL: process.env.PRODUCTOS_SERVICE_URL,
    REPORTES_SERVICE_URL: process.env.REPORTES_SERVICE_URL,
    PEDIDOS_SERVICE_URL: process.env.PEDIDOS_SERVICE_URL
};
