{{- if .Values.resourceQuota.enabled }}
apiVersion: v1
kind: ResourceQuota
metadata:
  name: sa-p5-quota
  labels:
    {{- include "sa-p5.labels" . | nindent 4 }}
spec:
  hard:
    {{- range $key, $value := .Values.resourceQuota.hard }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
{{- end }}
