services:

  postgres:
    image: postgres:17-alpine
    container_name: sa_p2_postgres

    restart: unless-stopped

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: aut

    ports:
      - "5434:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/01_init.sql:/docker-entrypoint-initdb.d/01_init.sql

  authz-service:
    build: ./authz-service
    container_name: sa_p2_authz

    restart: unless-stopped

    ports:
      - "4000:4000"

    env_file:
      - ./authz-service/.env

    volumes:
      - ./authz-service:/app
      - /app/node_modules

    command: npm run dev

  backend:
    build: .

    container_name: sa_p2_backend

    restart: unless-stopped

    depends_on:
      - postgres
      - authz-service

    ports:
      - "3001:3000"

    env_file:
      - .env

    volumes:
      - .:/app
      - /app/node_modules

    command: npm run dev

volumes:
  postgres_data:
